# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hire',
            field=models.IntegerField(default=0),
        ),
    ]
